import numpy as np
import matplotlib.pyplot as plt
z = input("Enter title for the graph: ")
m = input("Enter lable on X-axis: ")
n = input("Enter lable on Y-axis: ")
x = input("Enter values on X-axis: ").split()
a = input("Enter lable for set1: ")
b = input("Enter lable for set2: ")
y1 = list(map(int, input("Enter values for 1st set: ").split()))
y2 = list(map(int, input("Enter values for 2nd set: ").split()))
X_axis = np.arange(len(x))
plt.bar(X_axis - 0.2, y1, 0.4, label = 'Girls')
plt.bar(X_axis + 0.2, y2, 0.4, label = 'Boys')
plt.xticks(X_axis, x)
plt.xlabel(m)
plt.ylabel(n)
plt.title(z)
plt.legend()
plt.show()
